[package]
name = "wayshot"
version = "0.1.0"
edition = "2021"
authors = ["Shinyzenith <aakash@shinyzenith.xyz>"]

[dependencies]
env_logger = "0.8.4"
evdev-rs = "0.5.0"
libc = "0.2.117"
log = "0.4.0"

[[bin]]
name = "bin"
path = "src/main.rs"
